/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nfdeneme;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author askilic
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form Newws
     */
    public SignIn() {
        initComponents();
        setTitle("Netflix application");
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    int id;
    public boolean enterence(String em , String pa){

            URL url2;
        try {
            url2 = new URL("http://80.211.50.23:4000/api/user");
            
            BufferedReader in = new BufferedReader(new InputStreamReader(url2.openStream()));
            String inputLine, result = "";
            while ((inputLine = in.readLine()) != null) {
                // System.out.println(inputLine);
                result += inputLine + "\n";                
            }
            //System.out.println(result);
            
            in.close();
            
            JSONParser jsp = new JSONParser();
            Object obj = jsp.parse(result);
            
            JSONArray jsa = (JSONArray) obj;
            String email = null;
            String pass = null;
            for(int i = 0;i<jsa.size();i++){
                JSONObject jso = (JSONObject) jsa.get(i);
                email =  jso.get("email").toString();
                pass = jso.get("pass").toString();
                id =  Integer.parseInt(jso.get("id").toString());
                if(em.equalsIgnoreCase(email)){
                    if(pa.equals(pass))
                        return true;
                }
            }         
        } catch (MalformedURLException ex) {
            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return false;
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoPanel = new javax.swing.JPanel();
        LogoNameLabel = new javax.swing.JLabel();
        LogoLabel = new javax.swing.JLabel();
        SignInPanel = new javax.swing.JPanel();
        PageIconLabel = new javax.swing.JLabel();
        SignUpLabel = new javax.swing.JLabel();
        mailLabel = new javax.swing.JLabel();
        mailTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        registerLabel = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();
        passwordSeparator = new javax.swing.JSeparator();
        mailSeparator = new javax.swing.JSeparator();
        enterMailSeparator = new javax.swing.JSeparator();
        enterPasswordSeparator = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoPanel.setBackground(new java.awt.Color(40, 36, 36));
        LogoPanel.setForeground(new java.awt.Color(40, 36, 36));
        LogoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoNameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nfdeneme/netflix-240.png"))); // NOI18N
        LogoPanel.add(LogoNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 250, 70));

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nfdeneme/netflix.png"))); // NOI18N
        LogoPanel.add(LogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 450));

        getContentPane().add(LogoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 500));

        SignInPanel.setBackground(new java.awt.Color(164, 0, 19));
        SignInPanel.setForeground(new java.awt.Color(164, 0, 19));
        SignInPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PageIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nfdeneme/Signin-account-96.png"))); // NOI18N
        SignInPanel.add(PageIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 0, -1, 80));

        SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nfdeneme/Singup-account-32.png"))); // NOI18N
        SignUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpLabelMouseClicked(evt);
            }
        });
        SignInPanel.add(SignUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        mailLabel.setBackground(new java.awt.Color(164, 0, 19));
        mailLabel.setFont(new java.awt.Font("Garuda", 1, 24)); // NOI18N
        mailLabel.setForeground(new java.awt.Color(40, 36, 36));
        mailLabel.setText("E-mail : ");
        SignInPanel.add(mailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        mailTextField.setBackground(new java.awt.Color(164, 0, 19));
        mailTextField.setFont(new java.awt.Font("Garuda", 1, 24)); // NOI18N
        mailTextField.setForeground(new java.awt.Color(40, 36, 36));
        mailTextField.setText("mail");
        mailTextField.setBorder(null);
        mailTextField.setSelectedTextColor(new java.awt.Color(40, 36, 36));
        mailTextField.setSelectionColor(new java.awt.Color(164, 0, 19));
        mailTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mailTextFieldMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mailTextFieldMouseClicked(evt);
            }
        });
        mailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailTextFieldActionPerformed(evt);
            }
        });
        SignInPanel.add(mailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 290, 50));

        passwordLabel.setBackground(new java.awt.Color(164, 0, 19));
        passwordLabel.setFont(new java.awt.Font("Garuda", 1, 24)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(40, 36, 36));
        passwordLabel.setText("Password : ");
        SignInPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        passwordTextField.setBackground(new java.awt.Color(164, 0, 19));
        passwordTextField.setFont(new java.awt.Font("Garuda", 1, 24)); // NOI18N
        passwordTextField.setForeground(new java.awt.Color(40, 36, 36));
        passwordTextField.setText("password");
        passwordTextField.setBorder(null);
        passwordTextField.setSelectedTextColor(new java.awt.Color(40, 36, 36));
        passwordTextField.setSelectionColor(new java.awt.Color(164, 0, 19));
        passwordTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordTextFieldMousePressed(evt);
            }
        });
        SignInPanel.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 290, 50));

        loginButton.setBackground(new java.awt.Color(164, 0, 19));
        loginButton.setFont(new java.awt.Font("Garuda", 1, 24)); // NOI18N
        loginButton.setForeground(new java.awt.Color(40, 36, 36));
        loginButton.setText("Login");
        loginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        SignInPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 90, -1));

        registerLabel.setBackground(new java.awt.Color(164, 0, 19));
        registerLabel.setFont(new java.awt.Font("Garuda", 3, 14)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(241, 233, 233));
        registerLabel.setText("To register, click on the icon :");
        SignInPanel.add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, 20));

        warningLabel.setBackground(new java.awt.Color(164, 0, 19));
        warningLabel.setFont(new java.awt.Font("Garuda", 3, 14)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(241, 233, 233));
        warningLabel.setText("Don't have an account? create one!");
        SignInPanel.add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, 20));

        passwordSeparator.setFont(new java.awt.Font("Garuda", 1, 18)); // NOI18N
        SignInPanel.add(passwordSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, 10));

        mailSeparator.setFont(new java.awt.Font("Garuda", 1, 18)); // NOI18N
        SignInPanel.add(mailSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 10));

        enterMailSeparator.setFont(new java.awt.Font("Garuda", 1, 18)); // NOI18N
        SignInPanel.add(enterMailSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 290, 10));

        enterPasswordSeparator.setFont(new java.awt.Font("Garuda", 1, 18)); // NOI18N
        SignInPanel.add(enterPasswordSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 290, 10));

        getContentPane().add(SignInPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 310, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailTextFieldActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_mailTextFieldActionPerformed

    private void SignUpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpLabelMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        SignUp nj = new SignUp();
        nj.setVisible(true);
        
    }//GEN-LAST:event_SignUpLabelMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:

        
        
        String lmail = mailTextField.getText();
        System.out.println("lmail : "+lmail);
        String lpass = passwordTextField.getText();
        System.out.println("lpass : "+lpass);

        if(enterence(lmail, lpass)){
        this.setVisible(false);
        NetFlix nf = new NetFlix(id);
        nf.setVisible(true);
        }
        else if (lmail.equals("") || lpass.equals("")){
                JOptionPane.showMessageDialog(null,"Mail or Password is not fiiled!!");
        }   
        else JOptionPane.showMessageDialog(null,"Wrong Mail or Password");
             
    }//GEN-LAST:event_loginButtonActionPerformed

    private void mailTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailTextFieldMousePressed
        // TODO add your handling code here:
        mailTextField.setText("");
    }//GEN-LAST:event_mailTextFieldMousePressed

    private void mailTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailTextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mailTextFieldMouseClicked

    private void passwordTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTextFieldMousePressed
        // TODO add your handling code here:
        passwordTextField.setText("");
    }//GEN-LAST:event_passwordTextFieldMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SignIn().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JLabel LogoNameLabel;
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JLabel PageIconLabel;
    private javax.swing.JPanel SignInPanel;
    private javax.swing.JLabel SignUpLabel;
    private javax.swing.JSeparator enterMailSeparator;
    private javax.swing.JSeparator enterPasswordSeparator;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JSeparator mailSeparator;
    private javax.swing.JTextField mailTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JSeparator passwordSeparator;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
